netty:
  server:
    host: localhost
    port: 6000
    connectionThreads: 1
    dataProcessThreads: 10
    timeoutSeconds: 50

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signum
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
