netty:
  server:
    host: localhost
    port: 6001
    connectionThreads: 1
    dataProcessThreads: 10
    timeoutSeconds: 300
  contextManager:
    lifecycleObserver:
      responseTimeoutSeconds: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signum
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true


message:
  validation:
    minValidAmountSatellite: 3
    maxValidDOP: 7
