netty:
  server:
    host: localhost
    port: 6001
    connectionThreads: 1
    dataProcessThreads: 10
    timeoutSeconds: 300
  contextManager:
    lifecycleObserver:
      responseTimeoutSeconds: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signum
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092


message:
  validation:
    minValidAmountSatellite: 3
    maxValidAmountSatellite: 999
    minValidDOP: 0
    maxValidDOP: 7

kafka:
  topic:
    inbound-messages:
      name: signum-messages
      partitions-amount: 1
      replication-factor: 1
      producer:
        batch-size: 10
        linger-ms: 500
        delivery-timeout-ms: 100000
      consumer:
        group-id: signum-messages-group
    saved-messages:
      name: signum-messages-main
      partitions-amount: 1
      replication-factor: 1




